version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  publish-service:
    build:
      context: ./services/publish-service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./services/publish-service/uploads:/tmp/uploads
    environment:
      - NODE_ENV=production
      - PORT=5005
      - SESSION_SECRET=your-super-secret-session-key-here
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3000
      # Add your OAuth credentials here
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
      # Add other OAuth credentials as needed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - publish-service
    environment:
      - VITE_API_URL=http://localhost:5005
    restart: unless-stopped